In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter

df = pd.read_csv("reviews_748_clasificadas.csv")
df["categorias_lista"] = df["categorias"].apply(
    lambda s: [c.strip() for c in str(s).split(";") if c.strip()] if pd.notna(s) else []
)

df["anio"] = pd.to_datetime(df["fecha_iso"]).dt.year

CATEGORIAS = [
    "delays",
    "inappropriate_interpersonal_behavior",
    "inefficient_medical_treatment",
    "bad_infrastructure",
    "incorrect_diagnoses",
    "other",
]

print(f"Cargadas {len(df)} reseñas")
print(f"Hospitales: {df['hospital'].unique().tolist()}")
print(f"Años: {sorted(df['anio'].unique().tolist())}")
df.head()

Cargadas 748 reseñas
Hospitales: ['Alvarez', 'Penna', 'Durand', 'Argerich', 'Rivadavia']
Años: [2023, 2024, 2025]

,hospital,autor,es_local_guide,rating,fecha_relativa,fecha_iso,fuente,texto,respuesta_negocio,anio,ai_guess,categorias,categorias_lista
0,Alvarez,PATO ISA,NaN,1.0,Hace 8 meses,2025-10-29T10:02:19Z,Google,Ayer estuve en el Hospital Álvarez con mi cuña...,NaN,2025,"['delays', 'inappropriate_interpersonal_behavi...",delays; inappropriate_interpersonal_behavior,"[delays, inappropriate_interpersonal_behavior]"
1,Alvarez,afgan lacsai,NaN,1.0,Hace un año,2025-04-12T07:42:46Z,Google,"Desastre total la atención, la traje a mi pare...",NaN,2025,"['delays', 'inappropriate_interpersonal_behavi...",delays; inappropriate_interpersonal_behavior,"[delays, inappropriate_interpersonal_behavior]"
2,Alvarez,Maximiliano Campos,NaN,1.0,Hace un año,2024-07-11T01:57:06Z,Google,Un desastre. Realmente un desastre. Fuimos con...,NaN,2024,['inappropriate_interpersonal_behavior'],inappropriate_interpersonal_behavior,[inappropriate_interpersonal_behavior]
3,Alvarez,Sarita de Lourdes CaceresChambergo,NaN,1.0,Hace 11 meses,2025-07-09T09:32:49Z,Google,Un desastre de admisión estuvieron haciendo es...,NaN,2025,"['delays', 'inappropriate_interpersonal_behavi...",delays; inappropriate_interpersonal_behavior,"[delays, inappropriate_interpersonal_behavior]"
4,Alvarez,Valen HakimiaN,NaN,1.0,Hace 6 meses,2025-12-25T20:06:14Z,Google,"es una vergüenza este hospital, hace 3hs que e...",NaN,2025,"['delays', 'inappropriate_interpersonal_behavi...",delays; inappropriate_interpersonal_behavior,"[delays, inappropriate_interpersonal_behavior]"

In [3]:
total = len(df)
conteo = Counter(cat for lista in df["categorias_lista"] for cat in lista)

tabla = pd.DataFrame(
    [(cat, n, n/total*100) for cat, n in conteo.most_common()],
    columns=["categoria", "cantidad_filas", "porcentaje"]
)
tabla["porcentaje"] = tabla["porcentaje"].round(1)

print(f"Total de reseñas: {total}\n")
print(tabla.to_string(index=False))

Total de reseñas: 748

                           categoria  cantidad_filas  porcentaje
                              delays             414        55.3
inappropriate_interpersonal_behavior             380        50.8
       inefficient_medical_treatment             129        17.2
                               other             123        16.4
                  bad_infrastructure             122        16.3
                 incorrect_diagnoses              33         4.4

In [4]:
#Let's see how is this percentage but by hospital

In [5]:
filas = []
for hosp in df["hospital"].unique():
    sub = df[df["hospital"] == hosp]
    total_hosp = len(sub)
    conteo = Counter(cat for lista in sub["categorias_lista"] for cat in lista)
    fila = {"hospital": hosp, "total_reviews": total_hosp}
    for cat in CATEGORIAS:
        fila[cat] = round(conteo.get(cat, 0) / total_hosp * 100, 1)
    filas.append(fila)

tabla_hosp = pd.DataFrame(filas).set_index("hospital")
print("Porcentaje de reseñas que menciona cada categoría, por hospital (%):\n")
print(tabla_hosp.to_string())

Porcentaje de reseñas que menciona cada categoría, por hospital (%):

           total_reviews  delays  inappropriate_interpersonal_behavior  inefficient_medical_treatment  bad_infrastructure  incorrect_diagnoses  other
hospital
Alvarez              168    46.4                                  61.9                           17.9                 8.9                  4.2   16.7
Penna                125    59.2                                  46.4                           13.6                16.8                  4.0   15.2
Durand               191    58.6                                  47.1                           26.7                21.5                  5.2   15.2
Argerich             163    57.7                                  45.4                           10.4                14.1                  2.5   21.5
Rivadavia            101    55.4                                  53.5                           13.9                21.8                  6.9   11.9

In [6]:
tabla_hosp = pd.DataFrame(filas).set_index("hospital")
tabla_hosp

,total_reviews,delays,inappropriate_interpersonal_behavior,inefficient_medical_treatment,bad_infrastructure,incorrect_diagnoses,other
hospital,,,,,,,
Alvarez,168,46.4,61.9,17.9,8.9,4.2,16.7
Penna,125,59.2,46.4,13.6,16.8,4.0,15.2
Durand,191,58.6,47.1,26.7,21.5,5.2,15.2
Argerich,163,57.7,45.4,10.4,14.1,2.5,21.5
Rivadavia,101,55.4,53.5,13.9,21.8,6.9,11.9

In [7]:
#2025 (last year)

In [9]:
df_2025 = df[df["anio"] == 2025]

filas = []
for hosp in df_2025["hospital"].unique():
    sub = df_2025[df_2025["hospital"] == hosp]
    total_hosp = len(sub)
    conteo = Counter(cat for lista in sub["categorias_lista"] for cat in lista)
    fila = {"hospital": hosp, "total_reviews": total_hosp}
    for cat in CATEGORIAS:
        fila[cat] = round(conteo.get(cat, 0) / total_hosp * 100, 1)
    filas.append(fila)

tabla_2025 = pd.DataFrame(filas).set_index("hospital")

print(f"Total de reseñas de 2025: {len(df_2025)}")
tabla_2025

Total de reseñas de 2025: 271

,total_reviews,delays,inappropriate_interpersonal_behavior,inefficient_medical_treatment,bad_infrastructure,incorrect_diagnoses,other
hospital,,,,,,,
Alvarez,54,48.1,68.5,20.4,3.7,3.7,20.4
Penna,53,56.6,52.8,18.9,20.8,5.7,15.1
Durand,64,56.2,48.4,26.6,21.9,1.6,15.6
Argerich,63,55.6,50.8,7.9,7.9,1.6,23.8
Rivadavia,37,43.2,62.2,21.6,8.1,10.8,13.5

In [12]:
df["anio"] = pd.to_datetime(df["fecha_iso"]).dt.year
filtro = df[
    (df["hospital"] == "Alvarez") &
    (df["ai_guess"].apply(lambda l: "inappropriate_interpersonal_behavior" in l)) &
    (df["anio"] == 2025)
]

print(f"Reseñas del Alvarez con inappropriate_interpersonal_behavior en 2025: {len(filtro)}\n")

for i, row in filtro.iterrows():
    print(f"[{row['fecha_iso'][:10]} — rating {row['rating']}]")
    print(f"Categorías: {row['ai_guess']}")
    print(row["texto"])
    print("-" * 80)

Reseñas del Alvarez con inappropriate_interpersonal_behavior en 2025: 37

[2025-10-29 — rating 1.0]
Categorías: ['delays', 'inappropriate_interpersonal_behavior']
Ayer estuve en el Hospital Álvarez con mi cuñado, que es esquizofrénico. Estaba en crisis, quería suicidarse, y se cayó, fracturándose el brazo izquierdo. Desde las 13 hs hasta las 19 hs nadie nos atendió. Se cayó al piso y ni el camillero ni los médicos se acercaron; pasaban por su lado y se reían. Nadie nos ayudó. Después de seis horas nos atendió un supuesto psiquiatra, que hizo las recetas de los medicamentos utilizando los sellos de una doctora.
No me interesa si no me dan importancia acá, pero voy a exponer esto en todos lados. Son unos sinvergüenzas; los síndicos tienen cero empatía
--------------------------------------------------------------------------------
[2025-04-12 — rating 1.0]
Categorías: ['delays', 'inappropriate_interpersonal_behavior']
Desastre total la atención, la traje a mi pareja a las 3 de la mañana luego de haber sido atendida el día anterior por dolor abdominal, le dijeron q venga si levantaba fiebre. Levanto fiebre y tuvo vómitos y desde las, ya son las 04.40 y aun no la atendieron, no hay nadie más en la guardia!!! Es la que sigue, ya la van a atender, es lo único que repetía la de admisión. Se cagan en el sufrimiento ajeno. Los doctores durmiendo tranquilamente mientras en la guardia mi pareja se retuerce de los dolores. Impresentables
--------------------------------------------------------------------------------
[2025-07-09 — rating 1.0]
Categorías: ['delays', 'inappropriate_interpersonal_behavior']
Un desastre de admisión estuvieron haciendo esperar más 1 hora para ingresar mis datos y mentirosos al decir  q estuvieron hay todo el tiempo. Durmieron durante la noche y cuando se despertaron recién atendieron. Esta chica y su compañero son los q tienen pésima atención
--------------------------------------------------------------------------------
[2025-12-25 — rating 1.0]
Categorías: ['delays', 'inappropriate_interpersonal_behavior']
es una vergüenza este hospital, hace 3hs que estoy esperando y llamaron a dos personas. Entro una chica agonizadando del dolor y la dejaron ahi nomas en una silla de ruedeas esperando. Si tenes una urgenica no vengas NUNCA.
Demás esta decir q las de recepción te atienden de mala manera y con odio
--------------------------------------------------------------------------------
[2025-09-19 — rating 1.0]
Categorías: ['inappropriate_interpersonal_behavior']
Pesima , pesima atencion por parte de la infectologa Rosana Lujan Cuini, por discriminacion , mi mama se presento para ser atendida ya que tiene TBC y esta con tratamiento por ende no contagia y con las medidas de seguridad usando barbijo y alcohol en gel en mano , fue rechazada la atencion  por parte d esta supuesta Doctora
Le falta vocacion y ganas muchas ganas de trabajar . Dediquese a otra cosa .
--------------------------------------------------------------------------------
[2025-10-29 — rating 1.0]
Categorías: ['delays', 'inefficient_medical_treatment', 'inappropriate_interpersonal_behavior']
Una porquería de hospital. Los supuestos medicos no lo son. Son extranjeros que no te dicen sus apellidos para que uno no los expongan. Fuimos hoy a las 2 de la tarde y estuvimos hasta las 8 de la noche. Como llegamos nos fuimos. sin ninguna solucion. Llevamos a mi hermano esquizofrenico con una orden de su psiquiatra Dra Buttman para internarlo y se negaron a hacerlo diciendonos textualmente: " A mi una psiquiatra no me va a dar a órdenes". Realmente deprimente la atención del hospital. Ojalá los echen a todos porque ninguno sirve para nada...Desde la recepcion hasta los supuestos medicos é irrespetuosos. Ni siquiera te dicen sus nombres para que uno no los pueda escrachar en las redes. Mi hermano se llama Carlos Gies y lo mandaron de vuelta a su casa en condiciones deplorables sin atenderlo adecuadamente. Hasta desconfiaron de las cosas que les decíamos sobre lo que nos estaba pasando. Les dijimos que él se stiende ahi desde hace 15 años y nos trataron de mentirosos. Mi hermano gritaba y estaba tirado en el piso y ni siquiera quisieron levantarlo para ayudarlo. Son inhumanos y muy pocos profesionales.  Piden aumento de sueldo pero no merecen ni siquiera lo que cobran ahora por cómo atienden a los pacientes. Esto tiene que cambiar.
--------------------------------------------------------------------------------
[2025-09-30 — rating 1.0]
Categorías: ['inefficient_medical_treatment', 'inappropriate_interpersonal_behavior']
Fui a la guardia esta tarde con taquicardia, dolor de pecho y sin poder respirar bien, me enviaron a un médico rápido por suerte pero este mismo médico ni me reviso ni nada... me contesto pésimo diciendo que no había que molestar a la guardia si no era una urgencia (no sabia si lo mio era una urgencia porque ni me reviso) y sigo exactamente con los mismos síntomas... solo me dio clonazepam para calmar los nervios, literalmente

Y ahora que estoy mirando el medico que me atendió supuestamente es un traumatologo (alejandro tabbaj), nada que ver con lo que yo necesitaba pero bueno, gracias por su mala atención. La próxima a un particular claramente porque no sirven para nada
--------------------------------------------------------------------------------
[2025-07-08 — rating 1.0]
Categorías: ['delays', 'inappropriate_interpersonal_behavior']
Una hora y media esperando y ni siquiera habían atendido a la otra gente que encima era gente grande. Horrible y encima el recepcionista ese se fue como por dos horas o más y no atendían a la gente
--------------------------------------------------------------------------------
[2025-02-26 — rating 1.0]
Categorías: ['inappropriate_interpersonal_behavior']
El peor hospital para tener un hijo, fui hacer mi primera eco y cero intimidad y mientras antes te puedan sacar de encima mejor, arruinaron mi primer eco y el escuchar sus latidos, nunca mas. Y en la guardia las trataban con una violencia a una mamá primeriza,  entiendo q para ustedes es algo de todos los días pero para q carajo estudian si van a tener cero paciencia con la gente. Un horror todo
--------------------------------------------------------------------------------
[2025-01-25 — rating 1.0]
Categorías: ['inappropriate_interpersonal_behavior', 'delays']
Un maleducado el chico de recepción con barba, le voy a preguntar y me dice que no pregunte boludeces. La sala a medio vacío y aún así hay demora. No vengan acá. Es puro dolor de cabeza
--------------------------------------------------------------------------------
[2025-09-17 — rating 1.0]
Categorías: ['delays', 'inappropriate_interpersonal_behavior']
me gustaría que se capacitara a los médicos de guardia sobre como tratar a los colegas que van a presentar pacientes, dado que por mucho que llegase a estar colapsada la urgencia, tienen que informarle al medico de la ambulancia de forma respetuosa que no lo pueden aceptar y para no afectar al paciente determinar si requieren o no realizarle formato de rechazo para que la obra social pueda redireccionar a la ambulancia.
tienen que colocarse en el lugar del medico que esta trasladando quien también esta haciendo su trabajo y no decide donde llevar al paciente.
una medico clínica de guardia de nacionalidad ecuatoriana cabello tinturado de rubio y gafas rojas , a la que al decirle buenas noches solo me levanto la voz  gritándome que estaba colapsada y que no lo podía aceptar, de la clínica solo me dejo decir muy poco quedandose solo con la idea de que estaba hipotenso y me grito que antes de derivarlo debía administrarle 2000 de lev sin escuchar como tal las condiciones del paciente (traumatismo craneoencefalico) , se les olvida que quien traslada es un medico y tambien sabe como manejar a un paciente.
al explicarle que necesitaba el rechazo para ubicar al paciente me grito que no lo iba a hacer , al decirle que me podia rechazar al paciente de forma amable y respetuosa recordandole que somos colegas me dijo que ya me estaba respetando mucho e inclusive me manoteo , con sus palabras y actitud fácilmente me podía agredir físicamente.
una hora esperando el rechazo por parte del medico y llamando a cabina para que por favor se me eximiera la presentación de rechazo para poder reubicar al paciente logrando así trasladarlo

POR FAVOR SOMOS COLEGAS, PROFESIONALES Y ATENDEMOS PERSONAS
pongámonos en el lugar del paciente descompensado que requiere atención, el familiar que esta lleno de angustia y el medico de la ambulancia que ante la ausencia de recursos esta contabilizando el tiempo para evitar una mayor complicación.

que residentes de clínica de primer año estén acompañados de un superior que sepa manejar el servicio para que se priorice el buen trato.

ojala y esto sirva de algo.
--------------------------------------------------------------------------------
[2025-10-10 — rating 1.0]
Categorías: ['delays', 'inefficient_medical_treatment', 'inappropriate_interpersonal_behavior']
La verdad que la guardia una decepción atendían cada dos hrs yo llegue a las 3 y había gente desde las 9 de la mañana esperando yo soy discapacitada y no me atendieron como prioridad una mujer se desmayo y ni bola los médicos .nos atendieron tipo 8:30 pero como descarte ahí mismo en recepción yo vengo descompuesta hace 4 meses y ahora con sangre no me chequearon ni me mandaron a ser estudios y peor aún me recetaron una pastilla que ya la había tomado y no me hace nada .una chica vomitaba sangre le dió pastilla y la mando a su casa .yo soy de oeste y pague Uber para ir y volver ese hospital debería ser clausurado está en el centro y es una vergüenza ni en las salitas te tratan así .
--------------------------------------------------------------------------------
[2025-09-19 — rating 1.0]
Categorías: ['inappropriate_interpersonal_behavior', 'inefficient_medical_treatment']
Quiero quejarme especialmente de la infectolga Rosana Lujan Cuini , por discriminación, la lleve a mi mamá que tiene TBC , para que pueda ser tratada x su enfermedad ya que no tolera medicacion , ella esta tomando antibióticos muy fuertes y necesitaba la ayuda d una profesional para una mejor evolución del tratamiento  y  con solo verla se negó rotundamente a atenderla . Ser Doctora no es solo tener un titulo sino tambien tener vocación y empatía . Gracias x nada . Pésima , pésima y pésima atención si se la puede llamar doctora .
--------------------------------------------------------------------------------
[2025-07-14 — rating 1.0]
Categorías: ['inefficient_medical_treatment', 'inappropriate_interpersonal_behavior']
Es un DESASTRE!!!!! Es la tercera vez que voy a la guardia con un dolor de pecho y espalda muy fuerte y no te dan ni 5 de pelota, ni te revisan, no te auscultan, no te sacan placas, no despegan el culo de la silla pero si te dan KETEROLAK inyectable sin notificarme ni preguntarme si soy alérgica. Una verdadera basura!!! El Director debería ocuparse, o es igual que los médicos de guardia?
--------------------------------------------------------------------------------
[2025-06-10 — rating 1.0]
Categorías: ['delays', 'inappropriate_interpersonal_behavior']
LA DOCTORA LORENA FERNANDEZ BISOGNIN , PEDIATRA,UN DESASTRE COMO PERSONA! PORQUE CUANDO SACAS TURNO TE DICEN LLEGAR MEDIA HORA ANTES! UNO LLEGA MEDIA HORA ANTES, Y LA DOCTORA CHARLANDO CON OTROS MEDICOS , TENIENDO PACIENTES EN ESPERA! UN DESASTRE !! Cuando le digo que lleve media hora antes , al turno asignado, se enoja porque dice que ella está atendiendo.
Y la veo charlando con otros médicos y se enoja y todavía TARDA MÁS PARA ATENDERME!! CERO PROFESIONALISMO!!
--------------------------------------------------------------------------------
[2025-08-16 — rating 1.0]
Categorías: ['inappropriate_interpersonal_behavior']
Un hospital que cuenta con los mejores especialistas, tantos pediatras y adultos. Tengan en admisión de adultos guardia turno noche a un desubicado prepotente que piensa que por sentarse detrás de un mostrador  pueden llevar por delantes a todo. Cero trato a las personas, cero empatía tendria que estar dedicandose a otra cosa. Esto es lamentable.
--------------------------------------------------------------------------------
[2025-04-06 — rating 1.0]
Categorías: ['incorrect_diagnoses', 'delays', 'inefficient_medical_treatment', 'inappropriate_interpersonal_behavior']
ACTUALIZACIÓN: A mi mamá la operaron de emergencia 2 meses después. ERA UNA APENDICITIS, no "PROBLEMAS PSICOLÓGICOS".

Falta de humildad del enfermero Julio y las médicas del turno.

El 25 de marzo a las 22 hs (todos veían el juego de argentina y brasil) llevé a mi mamá (50 años) a la guardia de este hospital luego de que perdiera el control de su cuerpo, sintiera una presión muy fuerte en el pecho y abdomen, y se quedara sin aire por unos segundos. Mientras nos acercábamos al hospital, volvió a debilitarse y a penas podia moverse, así que ingresé muy asustada, temiendo que fuera un ACV o un infarto.

El recepcionista, con total indiferencia, nos dijo que debíamos esperar. Un segundo después, mi mamá se desplomó delante de todos, sin responder a nuestros llamados. Con ayuda de otras personas la sostuvimos como pudimos. Golpeé la puerta de la guardia desesperada, mientras el recepcionista insistía en que debíamos esperar. Solo entonces salió Julio, el enfermero que realiza el triaje, nos dio una silla de ruedas y nos permitió ingresarla poco después.

En ese momento mi mamá no respondía, tenía la cabeza caída, balbuceaba y respiraba con dificultad. Julio me preguntó por qué no respondía a lo que el le preguntaba con arrogancia, y al decirle que se había desmayado, me contestó con soberbia: “No está desmayada”. Mamá  tenía el rostro  completamente pálido, la cara caída hacia un costado, no tenía fuerzas y minutos después comenzó a temblar, con las manos heladas, náuseas y vómitos. Le tomaron los signos vitales, que estaban dentro de parámetros normales, y Julio concluyó que lo único que iba a dejar asentado eran las náuseas. Según él, no había urgencia, era lo único que habia visto y debíamos esperar como todos.

Incluso insinuó que podía tratarse de algo psicológico.

Esperamos varias horas hasta que dos médicas nos llamaron. Apenas nos vieron entrar con la silla de ruedas, preguntaron con tono prepotente por qué estaba ahí. Les expliqué que se había desmayado y estaba muy débil, pero minimizaron lo ocurrido diciendo “eso no es un desmayo”. Hablaron todo el tiempo con cero empatía, y cuando mamá comentó que hace dos semanas no podía dormir bien, nuevamente insinuaron que debía buscar un psicólogo.

Le aplicaron una inyección de Reliverán y algo para el dolor. No le hicieron ni indicaron análisis. No le indicaron nada para dormir.

Dos días después fuimos a una clínica privada, donde la doctora le ordenó realizar unos 10 análisis y estudios.  Solo esperamos los resultados.

Lamentamos profundamente la falta de humanidad, escucha y criterio profesional con la que fuimos tratadas.
--------------------------------------------------------------------------------
[2025-03-31 — rating 1.0]
Categorías: ['inappropriate_interpersonal_behavior', 'delays']
La persona de admisión se va y deja sin atender el lugar.
Los enfermeros tienen un super destrato hacia las personas, sin causa. Simplemente se colocan en una posición de superioridad tratando despectivamente a los pacientes, sin brindar la información de forma clara. Fui con mi mamá a la guardia, le ordenaron laboratorio. 4 horas reloj esperando el resultado.
--------------------------------------------------------------------------------
[2025-09-01 — rating 1.0]
Categorías: ['inefficient_medical_treatment', 'incorrect_diagnoses', 'inappropriate_interpersonal_behavior']
Internacion de pediatría un desastre, pediatras unas inútiles 🙈 mi nena fue trasladada del garraham por cuadro asmático para esperar el término para el alta ingreso bien  y resultó que nos quedamos 3 días más exageraron la medicación y mi hija a las 24hs de su alta de ese hospital empeoró y la tuvimos que llevar al  Alvarez a ver qué nos responden y me dicen que el malestar que tenía era por el abrigo 🙈 así que la llevamos de vuelta al garraham al cual ingresó con ritmo cardiaco de 168 oxigeno 85 para ese momento los médicos no lo podían creer como reingreso , con neumonía bilateral , hígado un poco elevado las encinas por sobre medicación no adquirida 😥 que la tuvieron que poner vía endovenosa y oxígeno hasta mejorar en 5 días que por suerte estuvo con los mejores del garraham y salió perfectamente,  nunca más !!!!
--------------------------------------------------------------------------------
[2025-05-24 — rating 1.0]
Categorías: ['inappropriate_interpersonal_behavior']
Pésima atención y trato agresivo en recepción.
Mí hermano acudió a este hospital en busca de atención médica y en lugar de recibir ayuda, fue víctima del personal de recepción. Le sacaron el DNI a la fuerza, sin su consentimiento. Retener el DNI es un delito en nuestro país. Amenazaron con llamar a seguridad cuándo él no había hecho absolutamente nada malo, simplemente quería que lo admitan para que lo viera un médico. Yo estaba al teléfono, escuché como mi hermano peleaba para obtener de vuelta su DNI. La recepcionista preguntó mí nombre y apellido y dónde trabajaba, ya que sospechaba que "alguien nos había mandado". Es realmente preocupante, ¿estamos hablando de una mafia?
No pueden manejarse con tanta maldad e impunidad. Tomaré las medidas legales correspondientes.
Están destrozando al país. La impunidad de hoy en día es algo nunca visto.
--------------------------------------------------------------------------------
[2025-07-07 — rating 1.0]
Categorías: ['inappropriate_interpersonal_behavior']
Acaban de maltratarme en la recepción. Fui con fiebre y como tenía más de 72 hs me dijeron que era "para consultorio externo". Cuando le dije que eso no es correcto me dijeron y vos quien sos, sos médico?  Me maltrataron de una forma inhumana. 7 de julio del 2025.
--------------------------------------------------------------------------------
[2025-05-24 — rating 1.0]
Categorías: ['inappropriate_interpersonal_behavior', 'delays']
La administración de la guardia malisima, vine con síntomas que vienen perdurando hace días y empeorando. Cuando me atiene la señora me dice "hoy tenemos muchas urgencias, si ya estuviste con esos síntomas un par de días podes aguantar unos días más y venir otro día", no podes decir eso sin saber que tiene la persona, tuve que insistir para que me atiendan
--------------------------------------------------------------------------------
[2025-03-01 — rating 1.0]
Categorías: ['inappropriate_interpersonal_behavior']
Una vergüenza la que está en administración en la guardia es una maleducada está con celular y no quiere atender como corresponde. No me quiso dar un sartificado médico para mí trabajo. Anoche vine para guardia de trauma y me cuando quise pedi el sartificado a la ayer a la noche a las 21:30 me dijieron que faltaba que doctor complete los archivos y eso. Y la de administración me dijo venite mañana le decís la situación así te dan un sartificado. Fui hace un rato a las 9:00 a la guardia y la de administración una maleducada, me dijo que no se podía que se hace en el momento. Le quise mostrar la receta del doctor y mi DNI para que vea en el sistema mi ingreso de ayer que fue a las 20:30. Y me dijo que no se puede, que no importa. Y no me miraba. Miraba su celular y no quería ni entrar al sistema. Una maleducada te hablan mal y está con el celular mientras te habla. Una vergüenza.
--------------------------------------------------------------------------------
[2025-08-04 — rating 1.0]
Categorías: ['inefficient_medical_treatment', 'inappropriate_interpersonal_behavior']

In [14]:
fragmento = "podes aguantar unos días más"

encontrada = df[df["texto"].str.contains(fragmento, case=False, na=False)]

print(f"Reseñas encontradas: {len(encontrada)}\n")
for i, row in encontrada.iterrows():
    print(f"Hospital: {row['hospital']}")
    print(f"Fecha exacta: {row['fecha_iso']}")
    print(f"Fecha relativa: {row['fecha_relativa']}")
    print(f"Rating: {row['rating']}")
    print(f"Autor: {row['autor']}")
    print(f"Categorías IA: {row['ai_guess']}")
    print(f"\nTexto completo:\n{row['texto']}")

Reseñas encontradas: 1

Hospital: Alvarez
Fecha exacta: 2025-05-24T17:29:36Z
Fecha relativa: Hace un año
Rating: 1.0
Autor: angelo
Categorías IA: ['inappropriate_interpersonal_behavior', 'delays']

Texto completo:
La administración de la guardia malisima, vine con síntomas que vienen perdurando hace días y empeorando. Cuando me atiene la señora me dice "hoy tenemos muchas urgencias, si ya estuviste con esos síntomas un par de días podes aguantar unos días más y venir otro día", no podes decir eso sin saber que tiene la persona, tuve que insistir para que me atiendan

In [16]:
df["anio"] = pd.to_datetime(df["fecha_iso"]).dt.year

filtro = df[
    (df["hospital"] == "Durand") &
    (df["ai_guess"].apply(lambda l: "inefficient_medical_treatment" in l)) &
    (df["anio"] == 2025)
]

print(f"Reseñas del Durand con inefficient_medical_treatment en 2025: {len(filtro)}\n")

for i, row in filtro.iterrows():
    print(f"[{row['fecha_iso'][:10]} — rating {row['rating']}]")
    print(f"Categorías: {row['ai_guess']}")
    print(row["texto"])
    print("-" * 80)

Reseñas del Durand con inefficient_medical_treatment en 2025: 17

[2025-12-23 — rating 1.0]
Categorías: ['delays', 'inefficient_medical_treatment', 'inappropriate_interpersonal_behavior']
Si pudiera poner 0 estrellas lo haria...
2 horas por una reacción alérgica, importante...!!! Con edema facial y laringitis... tuvimos que ir a otro lugar porque se ponía cada vez peor!!!
Ponen en riesgo la vida de las personas, es hasta que les toque a ustedes!!!
La parte de admisión, una señora de la ventanilla 1... supuesto triage UNA COMPLETA VERGUENZA... no tiene la menor idea de lo que es una enfermedad potencialmente grave...!!!
--------------------------------------------------------------------------------
[2025-11-01 — rating 1.0]
Categorías: ['inefficient_medical_treatment', 'delays', 'inappropriate_interpersonal_behavior']
Debido a un esguince, fui a varios nosocomios y ninguno me brindó ayuda. En el Fernández, me despacharon diciendo que solo hiciera hielo y reposo, sin derivarme a kinesiología ni revisar lo inflamado que estaba mi pie!. Me dijeron que me coloque una bota que mañana podría trabajar y me enviaron de regreso.(??)
Luego, fui al Hospital de Clínicas y, la secretaria fue muy irrespetuosa, me indicó que, aunque estuviera fracturada, no me darían un turno. Fui a la guardia y, allí, me informaron que no había guardia desde un año atrás.;  y finalmente, en el Durán, acudí a un consultorio externo de traumatología,  para que un ser humano escriba en un papel" kinesiología"(son 2')y me dice con el celular en la mano vení el lunes, no me miró, estaba apurado para utilizar su celular, y como no tenía turno, no le importo en lo más mínimo
Fui nuevamente a la guardia y la secretaria me dijo que allí tampoco me derivarían. Entonces, me dirigí a la dirección y salieron dos señoras, una respetuosa y otra muy maleducada, que me dijeron que todo está muy legalizado:-¿qué pasa si te pasa algo? Yo sigo con el pie inflamado y dolorido, y ya es el día 15. Eso me pasa señora!!!
Todo esto es resultado de la falta de humanidad de todos ustedes, que están tan legalizados que parecen perder horas jugando con el celular. Nadie vigila al personal, y muchos se van a la hora que quieren. Todos ustedes dan vergüenza. ¿Alguna vez le hicieron un favor, SIN TURNO! aunque sea un minuto, a un familiar, amigo o conocido a través del nosocomio? Claro que si, y eso es legal!!!????
Tan legalizados que están, no se dedican a atender a los pacientes, sino a cubrirse entre ustedes y jugar con los celulares. Tienen tiempo, pero si un paciente hace una petición coherente, nunca la atienden.
Debería ser obligatorio que cada traumatólogo en guardia se tome un minuto para mirar el pie y otro minuto para derivarlo a kinesiología. Yo tengo que esperar un mes para que un traumatólogo me vea en consultorios externos, y así poder curar mi pie!.
En cuanto a la atención que recibí en clínica médica a la tarde, la semana pasada, una señora muy fría, maleducada e ignorante. A los directores de éstos nosocomios, les pregunto, por qué ejercen, tienen humanidad o van a jugar con el celular y cobrar un sueldo?.
--------------------------------------------------------------------------------
[2025-12-10 — rating 1.0]
Categorías: ['inappropriate_interpersonal_behavior', 'inefficient_medical_treatment']
Los doctores te tratan mal ! Vine por un cuadro viral y pq en mi trabajo alguien está contagiado de tuberculosis, le digo al doctor Martin Guamarini matrícula 77463 que me recomendaron de mi trabajo una radiografía y un estudio para descartar y me responde agresivamente que a él NO LE IMPORTA LO QUE ME DIJERON. No me reviso más que don minutos la espalda y me abrió la boca y alumbró la con su linterna mi garganta para ver la garganta. Hasta cuándo se seguirá evidenciando el maltrato  e irrespeto en la palabra y nadie dirá nada? Me voy con una fórmula medica para llenar mi cuerpo de basura sin un examen real.
--------------------------------------------------------------------------------
[2025-08-13 — rating 1.0]
Categorías: ['delays', 'inefficient_medical_treatment', 'bad_infrastructure', 'inappropriate_interpersonal_behavior']
Fui a atenderme por guardia.
La atención en recepción fue rapida, pero parecia que le estaba pidiendo un favor.
En la sala de espera habia 5 personas esperando luego de 4 horas ser antendidas y lamentablemente mucha gente en situación de calle utilizando la guardia para descansar seguros (ninguno genero inconveniente alguno y eran totalmente respetuosos e higienicos, aclaro por que en esta epoca de empatía nula es necesario).
Luego de que uno de estos pacientes reclame fueron a buscar al doctor y volvio a atender.con cara de dormido. En mi caso espere 45', pero fue solo por la oportuna intervención de este señor.
La atención por parte del medico fue buena y me dio todas las indicaciones correctamente.
Me parece incomprensible que para realizarme las placas tuve que subir escaleras o caminar medio hospital para poder usar un ascensor porque el de enfrente de guardia no funcionaba.
Ninguna queja sobre los profesionales, salvo el traumatólogo y su siesta, la infraestructura es pésima para una ciudad que tiene el mismo presupuesto que Roma y Madrid siendo 3 veces más chica y sin tener un Coliseo que mantener. Pesima la gestión del GCBA.
Aclaro también que comprendo al traumatologo que debe tener 3 trabajos para poder sobrevivir con salarios insultantes que le pagan.

***ACTUALIZACIÓN***

El medico nunca acomodó mi dedo de la luxación completamente y me envió a casa.
Al presentarme nuevamente en el hospital, me informan que debo operarme. Al ir a la oficina me contestan "SI SOS DE PROVINCIA, A LA PROVINCIA" de peor forma de la que suena.
Esta gente se cree que uno va a este horrible hospital y esta ciudad con olor a orina con gusto. Además de que no se hacen responsables de los errores cometidos por el propio hospital y sus empleados.
En vez de solucionar un problema, lo empeoraron, luego me discriminaron y al día de hoy no tengo respuesta de la nota presentada a la dirección del hospital.
Mi calificación de este hospital es nefasto y la atención administrativa es directamente de seres espantosos.
Los medicos tienen ganado el cielo, hasta deben dar explicaciones a pacientes por la pesima atención administrativa, y no solo es mi caso. Habia una persona que hacia 5 días era citada 8 hs para ser operada, realizando todas las preparaciónes, y las 5 veces le avisaron a las 12 hs que no quedaba tiempo de quirofano.
NEFASTO !
--------------------------------------------------------------------------------
[2025-10-06 — rating 1.0]
Categorías: ['delays', 'inefficient_medical_treatment', 'bad_infrastructure']
Horrible experiencia en el hospital durán tardaron 25 días en operarme una fractura de muñeca y codo y encima me operaron mal y me dejaron el dedo pulgar sin movilidad.
No estaban los puntos para sacar sin embargo me lo sacaron provocándome un desmayo.
Y para colmo pedí turno con el psicólogo sometiéndome a toda su burocracia de primero pedir turno con el médico clínico para que me derive con el psicólogo habiéndomedado una vez el turno para el psicólogo me dicen que no atienden de esa forma y que me comunique al 147 pido turno en el 147 y el día del turno me lo cancelan un desastre después se quejan de que les quitan subsidio a los hospitales.
--------------------------------------------------------------------------------
[2025-05-18 — rating 1.0]
Categorías: ['delays', 'inefficient_medical_treatment', 'bad_infrastructure', 'inappropriate_interpersonal_behavior']
Fue todo un espanto! Fui por dolores causados por el ciatico. Una noche que tenia toda mi zona izquierda sin sensibilidad. Espere 3 horas y 30 para que me atienda la guardia de traumatología, 3 veces tuve que pedir que me anuncien, no toleraba el dolor. Solo me inyectaron diclofenac y me dieron una pastilla "por si me duele" Parece placebo, no hace nada. Mas allá de la pesima atención, el lugar está en malisimas condiciones, muchisimo olor, los indigentes ocupando todos los asientos para dormir y peleandosé entre ellos dentro del establecimiento. Desde ya no volvería a ir, perdí mi tiempo.
--------------------------------------------------------------------------------
[2025-10-15 — rating 1.0]
Categorías: ['delays', 'inefficient_medical_treatment', 'inappropriate_interpersonal_behavior']
Llego con falta de aire y síntomas similares a un covid Me isopan dio negativo vuelvo a la guardia para ser atendido Pasaron más de 2 horas Consulte en ventanilla cuantos me quedaban delante me dijo 9...Hora y media después habían pasado como 15 incluso gente que había llegado después  Vuelvo a preguntar (de buena manera) y me dice ya me pregunto 2 veces ya lo van a llamar El tema es que me estaba ahogando A las cansadas me atienden Me dieron un antibiótico ligh.........Conclusión 3 horas más tarde internado con oxígeno y broncodilatadores Me inyectaron para estabilizarme Solo 1 estrella por el isopado y la placa
--------------------------------------------------------------------------------
[2025-07-04 — rating 1.0]
Categorías: ['delays', 'bad_infrastructure', 'inefficient_medical_treatment']
Un desastre, ayer fui a la guardia por presion alta, casi no habia nadie, me atendieron. Despues de esperar mas de 1 hora, y para mis 20 de presion me dieron un diuretico y me dijeron que esperara, hacia tanto frio y gente de la calle durmiendo en la sala de espera que me fui, iba a terminar agarrandome algunoa otra cosa, despues de mas hoar y media de espera me fui.
--------------------------------------------------------------------------------
[2025-09-03 — rating 1.0]
Categorías: ['incorrect_diagnoses', 'bad_infrastructure', 'inappropriate_interpersonal_behavior', 'inefficient_medical_treatment']
Una total desidia, la guardia médica es de lo peor, internaron a mi mamá, le dijeron neumonia,sin sacarle una placa, en una salida cuatro camillas, sin nada, gente en los pasillos tirada,  médicos,policías a las risas con los camilleros ,todos con celular era una fiesta para ellos la guardia medica,  soberbios como son los practicantes extranjeros, por suerte la pude trasladar, nada que ver con el diagnóstico,  no tenía neumonia! Desastroso caer ahi ! Un abandono
--------------------------------------------------------------------------------
[2025-01-23 — rating 1.0]
Categorías: ['inappropriate_interpersonal_behavior', 'inefficient_medical_treatment']
Mira que yo eh recorrido guardias pero jamás viví lo que me pasó hoy. La atención no llego a cero es menos 100 tenes fiebre me preocuntan le digo creo que si no tengo para medirme la temperatura, ah bueno entonces no tenes. No me tomaron nada ni un solo signo vital, no le dieron una sola receta, le digo me pueden aplicar algo no, anda a comprarte caramelos. El medico hace de fachero en vez de médico. Horrible
--------------------------------------------------------------------------------
[2025-01-13 — rating 1.0]
Categorías: ['inefficient_medical_treatment', 'delays', 'inappropriate_interpersonal_behavior']
EL PEOR HOSPITAL DE TODOS. Ni siquiera merece una estrella, dejaron morir a mi abuela. Llegamos por ACV y la dejaron sin asistencia toda una noche en una camilla en la guardia, no pasó ni 1 sola enfermera en toda la noche. Habían un montón de pacientes pidiendo asistencia a gritos. SUMANDO que todos tratan muy mal, cero empatía con los pacientes y acompañantes. FUE UNA VERDADERA PESADILLA.
--------------------------------------------------------------------------------
[2025-05-20 — rating 1.0]
Categorías: ['delays', 'inefficient_medical_treatment', 'inappropriate_interpersonal_behavior']
me habían dado ese papel para ir Sacar turno y verme no le pusieron nombre nada solo así como si nada voy para sacar turnos no hay vení el otro lunes te derivo a otro hospital para tu suerte no hay me basto ir dos veces osea tranki voy a trabajar con dolencia no se preocupe usted no se moleste en hacer un poco de esfuerzo te recetan algo para el dolor y a casa claro la atención muy guasa si fuera por mí los prendo fuego
--------------------------------------------------------------------------------
[2025-01-02 — rating 1.0]
Categorías: ['delays', 'inefficient_medical_treatment']
Lleve a mi hija con vomito. Mareo ÿ espere más de una hora que la atendieran. No la examinaron solo preguntaron por que había ido y le colocaron suero y le hicieron unos exámenes de laboratorio y salio igualita eso fue anoche 31 de diciembre y enferm
--------------------------------------------------------------------------------
[2025-06-12 — rating 1.0]
Categorías: ['inappropriate_interpersonal_behavior', 'inefficient_medical_treatment']
Estuve en el día de hoy 12/06/25 en la guardia de traumatología ,la atención pésima ,me mandó que tome total magnesiano ,lo peor es que no merecido ,y acota esto no es para traumatología,tendré que ver a un proctologo por un problema en la mano?patético este médico ,no sé quién le dio el diploma ,tengan cuidado .
--------------------------------------------------------------------------------
[2025-03-06 — rating 1.0]
Categorías: ['delays', 'inefficient_medical_treatment']
Horrible. Fui con terrible dolor de pelvis, me dio para hacerme análisis de orina, espere 3 HORAS, y nunca aparecieron con los resultados, tuve que volver a mi casa adolorida sin respuesta y a la madrugada.
Pésimo todo
--------------------------------------------------------------------------------
[2025-10-29 — rating 1.0]
Categorías: ['delays', 'inefficient_medical_treatment']
Me dan un turno para una lesión que tardaron un mes en contestar y un mes más en darme el turno, llego hoy y no me quisieron hacer la resonancia
--------------------------------------------------------------------------------
[2025-01-14 — rating 1.0]
Categorías: ['delays', 'inefficient_medical_treatment']
No la atendíron nunca y los doctores tomaban matesito .. me la lleve a otro lugar
--------------------------------------------------------------------------------

In [17]:
df["anio"] = pd.to_datetime(df["fecha_iso"]).dt.year
filtro = df[
    (df["hospital"] == "Durand") &
    (df["ai_guess"].apply(lambda l: "inefficient_medical_treatment" in l)) &
    (df["anio"] == 2025)
]

print(f"Reseñas del Durand con inefficient_medical_treatment en 2025: {len(filtro)}\n")

for i, row in filtro.iterrows():
    print(f"[{row['fecha_iso'][:10]} — rating {row['rating']}]")
    print(f"Categorías: {row['ai_guess']}")
    print(row["texto"])
    print("-" * 80)

Reseñas del Durand con inefficient_medical_treatment en 2025: 17

[2025-12-23 — rating 1.0]
Categorías: ['delays', 'inefficient_medical_treatment', 'inappropriate_interpersonal_behavior']
Si pudiera poner 0 estrellas lo haria...
2 horas por una reacción alérgica, importante...!!! Con edema facial y laringitis... tuvimos que ir a otro lugar porque se ponía cada vez peor!!!
Ponen en riesgo la vida de las personas, es hasta que les toque a ustedes!!!
La parte de admisión, una señora de la ventanilla 1... supuesto triage UNA COMPLETA VERGUENZA... no tiene la menor idea de lo que es una enfermedad potencialmente grave...!!!
--------------------------------------------------------------------------------
[2025-11-01 — rating 1.0]
Categorías: ['inefficient_medical_treatment', 'delays', 'inappropriate_interpersonal_behavior']
Debido a un esguince, fui a varios nosocomios y ninguno me brindó ayuda. En el Fernández, me despacharon diciendo que solo hiciera hielo y reposo, sin derivarme a kinesiología ni revisar lo inflamado que estaba mi pie!. Me dijeron que me coloque una bota que mañana podría trabajar y me enviaron de regreso.(??)
Luego, fui al Hospital de Clínicas y, la secretaria fue muy irrespetuosa, me indicó que, aunque estuviera fracturada, no me darían un turno. Fui a la guardia y, allí, me informaron que no había guardia desde un año atrás.;  y finalmente, en el Durán, acudí a un consultorio externo de traumatología,  para que un ser humano escriba en un papel" kinesiología"(son 2')y me dice con el celular en la mano vení el lunes, no me miró, estaba apurado para utilizar su celular, y como no tenía turno, no le importo en lo más mínimo
Fui nuevamente a la guardia y la secretaria me dijo que allí tampoco me derivarían. Entonces, me dirigí a la dirección y salieron dos señoras, una respetuosa y otra muy maleducada, que me dijeron que todo está muy legalizado:-¿qué pasa si te pasa algo? Yo sigo con el pie inflamado y dolorido, y ya es el día 15. Eso me pasa señora!!!
Todo esto es resultado de la falta de humanidad de todos ustedes, que están tan legalizados que parecen perder horas jugando con el celular. Nadie vigila al personal, y muchos se van a la hora que quieren. Todos ustedes dan vergüenza. ¿Alguna vez le hicieron un favor, SIN TURNO! aunque sea un minuto, a un familiar, amigo o conocido a través del nosocomio? Claro que si, y eso es legal!!!????
Tan legalizados que están, no se dedican a atender a los pacientes, sino a cubrirse entre ustedes y jugar con los celulares. Tienen tiempo, pero si un paciente hace una petición coherente, nunca la atienden.
Debería ser obligatorio que cada traumatólogo en guardia se tome un minuto para mirar el pie y otro minuto para derivarlo a kinesiología. Yo tengo que esperar un mes para que un traumatólogo me vea en consultorios externos, y así poder curar mi pie!.
En cuanto a la atención que recibí en clínica médica a la tarde, la semana pasada, una señora muy fría, maleducada e ignorante. A los directores de éstos nosocomios, les pregunto, por qué ejercen, tienen humanidad o van a jugar con el celular y cobrar un sueldo?.
--------------------------------------------------------------------------------
[2025-12-10 — rating 1.0]
Categorías: ['inappropriate_interpersonal_behavior', 'inefficient_medical_treatment']
Los doctores te tratan mal ! Vine por un cuadro viral y pq en mi trabajo alguien está contagiado de tuberculosis, le digo al doctor Martin Guamarini matrícula 77463 que me recomendaron de mi trabajo una radiografía y un estudio para descartar y me responde agresivamente que a él NO LE IMPORTA LO QUE ME DIJERON. No me reviso más que don minutos la espalda y me abrió la boca y alumbró la con su linterna mi garganta para ver la garganta. Hasta cuándo se seguirá evidenciando el maltrato  e irrespeto en la palabra y nadie dirá nada? Me voy con una fórmula medica para llenar mi cuerpo de basura sin un examen real.
--------------------------------------------------------------------------------
[2025-08-13 — rating 1.0]
Categorías: ['delays', 'inefficient_medical_treatment', 'bad_infrastructure', 'inappropriate_interpersonal_behavior']
Fui a atenderme por guardia.
La atención en recepción fue rapida, pero parecia que le estaba pidiendo un favor.
En la sala de espera habia 5 personas esperando luego de 4 horas ser antendidas y lamentablemente mucha gente en situación de calle utilizando la guardia para descansar seguros (ninguno genero inconveniente alguno y eran totalmente respetuosos e higienicos, aclaro por que en esta epoca de empatía nula es necesario).
Luego de que uno de estos pacientes reclame fueron a buscar al doctor y volvio a atender.con cara de dormido. En mi caso espere 45', pero fue solo por la oportuna intervención de este señor.
La atención por parte del medico fue buena y me dio todas las indicaciones correctamente.
Me parece incomprensible que para realizarme las placas tuve que subir escaleras o caminar medio hospital para poder usar un ascensor porque el de enfrente de guardia no funcionaba.
Ninguna queja sobre los profesionales, salvo el traumatólogo y su siesta, la infraestructura es pésima para una ciudad que tiene el mismo presupuesto que Roma y Madrid siendo 3 veces más chica y sin tener un Coliseo que mantener. Pesima la gestión del GCBA.
Aclaro también que comprendo al traumatologo que debe tener 3 trabajos para poder sobrevivir con salarios insultantes que le pagan.

***ACTUALIZACIÓN***

El medico nunca acomodó mi dedo de la luxación completamente y me envió a casa.
Al presentarme nuevamente en el hospital, me informan que debo operarme. Al ir a la oficina me contestan "SI SOS DE PROVINCIA, A LA PROVINCIA" de peor forma de la que suena.
Esta gente se cree que uno va a este horrible hospital y esta ciudad con olor a orina con gusto. Además de que no se hacen responsables de los errores cometidos por el propio hospital y sus empleados.
En vez de solucionar un problema, lo empeoraron, luego me discriminaron y al día de hoy no tengo respuesta de la nota presentada a la dirección del hospital.
Mi calificación de este hospital es nefasto y la atención administrativa es directamente de seres espantosos.
Los medicos tienen ganado el cielo, hasta deben dar explicaciones a pacientes por la pesima atención administrativa, y no solo es mi caso. Habia una persona que hacia 5 días era citada 8 hs para ser operada, realizando todas las preparaciónes, y las 5 veces le avisaron a las 12 hs que no quedaba tiempo de quirofano.
NEFASTO !
--------------------------------------------------------------------------------
[2025-10-06 — rating 1.0]
Categorías: ['delays', 'inefficient_medical_treatment', 'bad_infrastructure']
Horrible experiencia en el hospital durán tardaron 25 días en operarme una fractura de muñeca y codo y encima me operaron mal y me dejaron el dedo pulgar sin movilidad.
No estaban los puntos para sacar sin embargo me lo sacaron provocándome un desmayo.
Y para colmo pedí turno con el psicólogo sometiéndome a toda su burocracia de primero pedir turno con el médico clínico para que me derive con el psicólogo habiéndomedado una vez el turno para el psicólogo me dicen que no atienden de esa forma y que me comunique al 147 pido turno en el 147 y el día del turno me lo cancelan un desastre después se quejan de que les quitan subsidio a los hospitales.
--------------------------------------------------------------------------------
[2025-05-18 — rating 1.0]
Categorías: ['delays', 'inefficient_medical_treatment', 'bad_infrastructure', 'inappropriate_interpersonal_behavior']
Fue todo un espanto! Fui por dolores causados por el ciatico. Una noche que tenia toda mi zona izquierda sin sensibilidad. Espere 3 horas y 30 para que me atienda la guardia de traumatología, 3 veces tuve que pedir que me anuncien, no toleraba el dolor. Solo me inyectaron diclofenac y me dieron una pastilla "por si me duele" Parece placebo, no hace nada. Mas allá de la pesima atención, el lugar está en malisimas condiciones, muchisimo olor, los indigentes ocupando todos los asientos para dormir y peleandosé entre ellos dentro del establecimiento. Desde ya no volvería a ir, perdí mi tiempo.
--------------------------------------------------------------------------------
[2025-10-15 — rating 1.0]
Categorías: ['delays', 'inefficient_medical_treatment', 'inappropriate_interpersonal_behavior']
Llego con falta de aire y síntomas similares a un covid Me isopan dio negativo vuelvo a la guardia para ser atendido Pasaron más de 2 horas Consulte en ventanilla cuantos me quedaban delante me dijo 9...Hora y media después habían pasado como 15 incluso gente que había llegado después  Vuelvo a preguntar (de buena manera) y me dice ya me pregunto 2 veces ya lo van a llamar El tema es que me estaba ahogando A las cansadas me atienden Me dieron un antibiótico ligh.........Conclusión 3 horas más tarde internado con oxígeno y broncodilatadores Me inyectaron para estabilizarme Solo 1 estrella por el isopado y la placa
--------------------------------------------------------------------------------
[2025-07-04 — rating 1.0]
Categorías: ['delays', 'bad_infrastructure', 'inefficient_medical_treatment']
Un desastre, ayer fui a la guardia por presion alta, casi no habia nadie, me atendieron. Despues de esperar mas de 1 hora, y para mis 20 de presion me dieron un diuretico y me dijeron que esperara, hacia tanto frio y gente de la calle durmiendo en la sala de espera que me fui, iba a terminar agarrandome algunoa otra cosa, despues de mas hoar y media de espera me fui.
--------------------------------------------------------------------------------
[2025-09-03 — rating 1.0]
Categorías: ['incorrect_diagnoses', 'bad_infrastructure', 'inappropriate_interpersonal_behavior', 'inefficient_medical_treatment']
Una total desidia, la guardia médica es de lo peor, internaron a mi mamá, le dijeron neumonia,sin sacarle una placa, en una salida cuatro camillas, sin nada, gente en los pasillos tirada,  médicos,policías a las risas con los camilleros ,todos con celular era una fiesta para ellos la guardia medica,  soberbios como son los practicantes extranjeros, por suerte la pude trasladar, nada que ver con el diagnóstico,  no tenía neumonia! Desastroso caer ahi ! Un abandono
--------------------------------------------------------------------------------
[2025-01-23 — rating 1.0]
Categorías: ['inappropriate_interpersonal_behavior', 'inefficient_medical_treatment']
Mira que yo eh recorrido guardias pero jamás viví lo que me pasó hoy. La atención no llego a cero es menos 100 tenes fiebre me preocuntan le digo creo que si no tengo para medirme la temperatura, ah bueno entonces no tenes. No me tomaron nada ni un solo signo vital, no le dieron una sola receta, le digo me pueden aplicar algo no, anda a comprarte caramelos. El medico hace de fachero en vez de médico. Horrible
--------------------------------------------------------------------------------
[2025-01-13 — rating 1.0]
Categorías: ['inefficient_medical_treatment', 'delays', 'inappropriate_interpersonal_behavior']
EL PEOR HOSPITAL DE TODOS. Ni siquiera merece una estrella, dejaron morir a mi abuela. Llegamos por ACV y la dejaron sin asistencia toda una noche en una camilla en la guardia, no pasó ni 1 sola enfermera en toda la noche. Habían un montón de pacientes pidiendo asistencia a gritos. SUMANDO que todos tratan muy mal, cero empatía con los pacientes y acompañantes. FUE UNA VERDADERA PESADILLA.
--------------------------------------------------------------------------------
[2025-05-20 — rating 1.0]
Categorías: ['delays', 'inefficient_medical_treatment', 'inappropriate_interpersonal_behavior']
me habían dado ese papel para ir Sacar turno y verme no le pusieron nombre nada solo así como si nada voy para sacar turnos no hay vení el otro lunes te derivo a otro hospital para tu suerte no hay me basto ir dos veces osea tranki voy a trabajar con dolencia no se preocupe usted no se moleste en hacer un poco de esfuerzo te recetan algo para el dolor y a casa claro la atención muy guasa si fuera por mí los prendo fuego
--------------------------------------------------------------------------------
[2025-01-02 — rating 1.0]
Categorías: ['delays', 'inefficient_medical_treatment']
Lleve a mi hija con vomito. Mareo ÿ espere más de una hora que la atendieran. No la examinaron solo preguntaron por que había ido y le colocaron suero y le hicieron unos exámenes de laboratorio y salio igualita eso fue anoche 31 de diciembre y enferm
--------------------------------------------------------------------------------
[2025-06-12 — rating 1.0]
Categorías: ['inappropriate_interpersonal_behavior', 'inefficient_medical_treatment']
Estuve en el día de hoy 12/06/25 en la guardia de traumatología ,la atención pésima ,me mandó que tome total magnesiano ,lo peor es que no merecido ,y acota esto no es para traumatología,tendré que ver a un proctologo por un problema en la mano?patético este médico ,no sé quién le dio el diploma ,tengan cuidado .
--------------------------------------------------------------------------------
[2025-03-06 — rating 1.0]
Categorías: ['delays', 'inefficient_medical_treatment']
Horrible. Fui con terrible dolor de pelvis, me dio para hacerme análisis de orina, espere 3 HORAS, y nunca aparecieron con los resultados, tuve que volver a mi casa adolorida sin respuesta y a la madrugada.
Pésimo todo
--------------------------------------------------------------------------------
[2025-10-29 — rating 1.0]
Categorías: ['delays', 'inefficient_medical_treatment']
Me dan un turno para una lesión que tardaron un mes en contestar y un mes más en darme el turno, llego hoy y no me quisieron hacer la resonancia
--------------------------------------------------------------------------------
[2025-01-14 — rating 1.0]
Categorías: ['delays', 'inefficient_medical_treatment']
No la atendíron nunca y los doctores tomaban matesito .. me la lleve a otro lugar
--------------------------------------------------------------------------------

In [19]:
fragmento = "terrible dolor de pelvis"

encontrada = df[df["texto"].str.contains(fragmento, case=False, na=False)]

print(f"Reseñas encontradas: {len(encontrada)}\n")
for i, row in encontrada.iterrows():
    print(f"Hospital: {row['hospital']}")
    print(f"Fecha exacta: {row['fecha_iso']}")
    print(f"Fecha relativa: {row['fecha_relativa']}")
    print(f"Rating: {row['rating']}")
    print(f"Autor: {row['autor']}")
    print(f"Categorías IA: {row['ai_guess']}")
    print(f"\nTexto completo:\n{row['texto']}")

Reseñas encontradas: 1

Hospital: Durand
Fecha exacta: 2025-03-06T05:54:52Z
Fecha relativa: Hace un año
Rating: 1.0
Autor: Yamila Ayelén Coria
Categorías IA: ['delays', 'inefficient_medical_treatment']

Texto completo:
Horrible. Fui con terrible dolor de pelvis, me dio para hacerme análisis de orina, espere 3 HORAS, y nunca aparecieron con los resultados, tuve que volver a mi casa adolorida sin respuesta y a la madrugada.
Pésimo todo

In [20]:
df["anio"] = pd.to_datetime(df["fecha_iso"]).dt.year
filtro = df[
    (df["hospital"] == "Rivadavia") &
    (df["ai_guess"].apply(lambda l: "bad_infrastructure" in l)) &
    (df["anio"] == 2025)
]

print(f"Reseñas del Rivadavia con bad_infrastructure en 2025: {len(filtro)}\n")

for i, row in filtro.iterrows():
    print(f"[{row['fecha_iso'][:10]} — rating {row['rating']}]")
    print(f"Categorías: {row['ai_guess']}")
    print(row["texto"])
    print("-" * 80)

Reseñas del Rivadavia con bad_infrastructure en 2025: 3

[2025-07-18 — rating 1.0]
Categorías: ['delays', 'bad_infrastructure']
Es increíble, son las 00:49hs. Llegamos a las 19:30 de la tarde y de repente nos dicen a todos los pacientes que estamos esperando hace más de 3hs y otros más que tenemos q salir afuera con terrible frío por qué tienen que "lavar los pisos". 00:49 de la noche! una locura y una vergüenza.
--------------------------------------------------------------------------------
[2025-08-11 — rating 1.0]
Categorías: ['inappropriate_interpersonal_behavior', 'bad_infrastructure']
Fui al área de vacunación porque tenía un turno y la chica estaba hablando con alguien en la puerta así que esperé detrás, a lo que terminó me tiró la puerta en la cara, toque varias veces la puerta y nunca me abrió. Fui a anunciarme de igual forma porque tenía turno y me dijeron que si mi receta era digital la tenía que llevar impresa, cuando saqué el turno no especificaba nada de eso, necesito la vacuna porque estoy embarazada, finalmente me fui, perdí el turno y no me vacuné. Los baños cagados.
--------------------------------------------------------------------------------
[2025-11-28 — rating 1.0]
Categorías: ['bad_infrastructure', 'inappropriate_interpersonal_behavior']
El hospital esta mal señalizado y el personal es muy grosero
--------------------------------------------------------------------------------

In [21]:
fragmento = "tienen que \"lavar los pisos\""

encontrada = df[df["texto"].str.contains(fragmento, case=False, na=False, regex=False)]

print(f"Reseñas encontradas: {len(encontrada)}\n")
for i, row in encontrada.iterrows():
    print(f"Hospital: {row['hospital']}")
    print(f"Fecha exacta: {row['fecha_iso']}")
    print(f"Fecha relativa: {row['fecha_relativa']}")
    print(f"Rating: {row['rating']}")
    print(f"Autor: {row['autor']}")
    print(f"Categorías IA: {row['ai_guess']}")
    print(f"\nTexto completo:\n{row['texto']}")

Reseñas encontradas: 1

Hospital: Rivadavia
Fecha exacta: 2025-07-18T03:56:49Z
Fecha relativa: Hace 11 meses
Rating: 1.0
Autor: Adrisol Palavecino
Categorías IA: ['delays', 'bad_infrastructure']

Texto completo:
Es increíble, son las 00:49hs. Llegamos a las 19:30 de la tarde y de repente nos dicen a todos los pacientes que estamos esperando hace más de 3hs y otros más que tenemos q salir afuera con terrible frío por qué tienen que "lavar los pisos". 00:49 de la noche! una locura y una vergüenza.

In [28]:
df["anio"] = pd.to_datetime(df["fecha_iso"]).dt.year
filtro = df[
    (df["hospital"] == "Rivadavia") &
    (df["ai_guess"].apply(lambda l: "incorrect_diagnoses" in l)) &
    (df["anio"] == 2025)
]

print(f"Reseñas del Rivadavia con incorrect_diagnoses en 2025: {len(filtro)}\n")

for i, row in filtro.iterrows():
    print(f"[{row['fecha_iso'][:10]} — rating {row['rating']}]")
    print(f"Categorías: {row['ai_guess']}")
    print(row["texto"])
    print("-" * 80)

Reseñas del Rivadavia con incorrect_diagnoses en 2025: 4

[2025-07-25 — rating 1.0]
Categorías: ['incorrect_diagnoses', 'inefficient_medical_treatment']
Ojo con este hospital te minimizan tu dolor y te mandan a tu casa si les toca un caso un poquito diferente al libro no saben que hacer.
Estoy viva de casualidad ya que me mandaron a mi casa porque tenia peditos según ellos y cuando voy al hospital penna me operan de urgencia ya que tenia algo mucho peor que peditos.
--------------------------------------------------------------------------------
[2025-02-18 — rating 1.0]
Categorías: ['inappropriate_interpersonal_behavior', 'delays', 'incorrect_diagnoses']
Hoy 18/02/25 a las 00:30 traje a mi sobrina con Trombosis en ambas piernas con fiebre y vomito le pedimos una silla de ruedas al "Recepcionista" y nos dijo que estaban todas ocupadas le dije que ella no podía caminar del dolor qué como quería que la entre. Me dijo que me fije yo en eso que ella entre como pueda o de lo contrario que vaya a otro hospital y que de igual manera no era seguro que la atiendan porque para el no era una urgencia. Entramos como pudimos le pedí que la ingrese y nos sentamos a esperar veíamos qué pasaba gente que había llegado después que nosotros mi hija le fue a preguntar porqué pasaba eso y el levantando la voz muy prepotente le dijo que el ya hizo su trabajo que no tiene porque darle explicaciones qué esperen o si querían podían irse ya habíamos esperado más de una hora nos dijo que ya estaba cargada para Traumatologia Le dije La trombosis le corresponde a un Medico Clínico! Ye me dijo que ya estaba ingresada qué el consideraba qué corresponde Traumatologia de lo contrario que lo cambie el Doctor cansado de su Prepotencia y falta de respeto le pedí el Libro de Actas para labrar una y me dijo que no había tal libro que venga a partir de las 08:00hs y que lo pida. Entonces lo invite a repetirme y a gritarme de este lado del mostrador si tenia Agallas y me dijo para que? Le dije para educarte cobarde y me dijo haber y que vas a hacer dale dale vení me decía dale seguía provocando obviamente lo re putie y me dijo ahora llamo a la policía para que te saque de acá. Vino la policía nos identifico le explique lo que pasó me dijo si ya se este siempre hace lo mismo y llama y tenemos que venir ni hablaron con el nos dijeron que vieron que somos personas educadas y se fueron. En Fin paso lo que ya sabíamos El Traumatologo atendió a mi Sobrina al ver su estado fue personalmente y trajo al medico Clínico y mi Sobrina quedó internada. Este tipo en el trascurso de tiempo que estuvimos esperando maltrató a una Embarazada a una anciana a una señora y a otro señor y a todos les decía que se Vayan a otro lado mientras tomaba mate y estaba con el Celular. Cuan acomodado puede estar este tipo? Quien lo puede estar bancando para que se maneje de esta manera con tanta impunidad? Gente dolorida desesperados por la salud de sus seres queridos tienen que soportar Prepotencia Insultos Gritos Ninguneos Burlas El señor de seguridad vino y se disculpo con nosotros por el mal momento. Ojalá que alguna Autoridad del Hospital se ponga al tanto de esta situación y tome alguna medida para que esta persona deje de Maltratar a todos los enfermos que vienen a este gran Hospital con tanta esperanza y trabaje como corresponde y si no está capacitado para el puesto que lo cambien a otro sector porque algún día se va a cruzar con alguien que sea más Violento que el y todo puede terminar muy mal.
--------------------------------------------------------------------------------
[2025-05-29 — rating 1.0]
Categorías: ['inappropriate_interpersonal_behavior', 'incorrect_diagnoses']
hay una doctora en la guardia, rubia con ojos celestes que te grita apenas te atiende de forma muy soberbia.
No podía responder a sus preguntas porque tenía la mitad de la cara para un costado, me dijo de una forma espantosa que lo que estaba haciendo era voluntario porque ninguna patología tenía ese síntoma (al menos yo no soy médico y no sabia lo que me estaba pasando porque además si fuese tan voluntario no lo estaría haciendo ni estaría perdiendo tiempo de vida en un hospital de mala muerte sin mencionar que me sentía mal)

Aclaro que me sentía mal por que  se ve que los medicos no saben que  si uno va a la guardia es porque no se siente bien.
Particularmente tengo que sentirme demasiado mal para ir a un médico porque pasan estás cosas.

Pero la cuestión es que me descompense en la calle: Unos policías me ayudaron y como no me sentía bien llamaron al same así caí en este hospital. Desconozco cómo se manejan en líneas generales, opino desde lo que me sucedió a mi, hay reseñas muy malas.

Con todo respeto doctora no se cómo te llamas porque ni siquiera te presentaste. Por médicos como vos la gente se queja del sistema de salud  del que vos misma sos parte y con motivos.
La función del médico es atender al paciente, explicar que sucede y darle un tratamiento si correspondiera. No es gritarle a quien se siente  horrible porque ni siquiera quiere estar ahí. Si lee esto doctora la justicia existe,  seguramente ni le interese pero los soberbios como usted tarda o temprano terminan pagando las consecuencias.

Está gente que no tiene las habilidades básicas para ejecutar su formación medica deberían sacarle la matrícula.
--------------------------------------------------------------------------------
[2025-04-03 — rating 1.0]
Categorías: ['delays', 'inappropriate_interpersonal_behavior', 'inefficient_medical_treatment', 'incorrect_diagnoses']
Mi experiencia fue muy mala. Lo único que sé del doctor es que se llama Darío. Fui porque tenía inflamada la garganta, me estaba agarrando fiebre, dolor de cabeza..y cuando tocó atenderme (no me quejo de la espera porque eso es "normal" en cualquier hospital) me vió así nomás la garganta, siquiera se fijó bien en el fondo que era lo que tenía que fijarse para ver qué tenía. Vio de lejos y después se fue. Cuando volvió, me dijo que era una "pavada", que con caramelitos que son buenos para la garganta se curan y básicamente, hablando en criollo, no me tomó en serio y me habló cómo si lo mío fuese una boludes. Aclaré que no me quejo del tiempo de espera sino que me parece una falta de respeto que después de esperar más de 2 hs me largue así nomás y sin una solución, más tratándome como si lo mío fuese una boludez y no es así. Me dijo que la "solución" era tomar paracetamol hasta que se me baje la fiebre y me banque el dolor de garganta por unos días hasta que se fuese solo. No puedo creer que pongan ése tipo de médicos para atender. 🤦🏼‍♂️🤦🏼‍♂️
Ahora estoy en otro hospital y estoy seguro que me va a dar un mejor diagnóstico y solución que esté sin vergüenza.
--------------------------------------------------------------------------------

In [29]:
fragmento = "tenia peditos según ellos"

encontrada = df[df["texto"].str.contains(fragmento, case=False, na=False, regex=False)]

print(f"Reseñas encontradas: {len(encontrada)}\n")
for i, row in encontrada.iterrows():
    print(f"Hospital: {row['hospital']}")
    print(f"Fecha exacta: {row['fecha_iso']}")
    print(f"Fecha relativa: {row['fecha_relativa']}")
    print(f"Rating: {row['rating']}")
    print(f"Autor: {row['autor']}")
    print(f"Categorías IA: {row['ai_guess']}")
    print(f"\nTexto completo:\n{row['texto']}")

Reseñas encontradas: 1

Hospital: Rivadavia
Fecha exacta: 2025-07-25T21:52:45Z
Fecha relativa: Hace 11 meses
Rating: 1.0
Autor: Hanna Gomez
Categorías IA: ['incorrect_diagnoses', 'inefficient_medical_treatment']

Texto completo:
Ojo con este hospital te minimizan tu dolor y te mandan a tu casa si les toca un caso un poquito diferente al libro no saben que hacer.
Estoy viva de casualidad ya que me mandaron a mi casa porque tenia peditos según ellos y cuando voy al hospital penna me operan de urgencia ya que tenia algo mucho peor que peditos.

In [30]:
filas = []
for hosp in df["hospital"].unique():
    sub = df[df["hospital"] == hosp]
    total = len(sub)
    conteo = Counter(cat for lista in sub["categorias_lista"] for cat in lista)
    for cat in CATEGORIAS:
        filas.append({
            "hospital": hosp,
            "categoria": cat,
            "porcentaje": round(conteo.get(cat, 0) / total * 100, 1)
        })

tabla_larga = pd.DataFrame(filas)
tabla_larga.to_csv("categorias_por_hospital_largo.csv", index=False, encoding="utf-8-sig")
print("Guardado: categorias_por_hospital_largo.csv")
tabla_larga

Guardado: categorias_por_hospital_largo.csv

     hospital                             categoria  porcentaje
0     Alvarez                                delays        46.4
1     Alvarez  inappropriate_interpersonal_behavior        61.9
2     Alvarez         inefficient_medical_treatment        17.9
3     Alvarez                    bad_infrastructure         8.9
4     Alvarez                   incorrect_diagnoses         4.2
5     Alvarez                                 other        16.7
6       Penna                                delays        59.2
7       Penna  inappropriate_interpersonal_behavior        46.4
8       Penna         inefficient_medical_treatment        13.6
9       Penna                    bad_infrastructure        16.8
10      Penna                   incorrect_diagnoses         4.0
11      Penna                                 other        15.2
12     Durand                                delays        58.6
13     Durand  inappropriate_interpersonal_behavior        47.1
14     Durand         inefficient_medical_treatment        26.7
15     Durand                    bad_infrastructure        21.5
16     Durand                   incorrect_diagnoses         5.2
17     Durand                                 other        15.2
18   Argerich                                delays        57.7
19   Argerich  inappropriate_interpersonal_behavior        45.4
20   Argerich         inefficient_medical_treatment        10.4
21   Argerich                    bad_infrastructure        14.1
22   Argerich                   incorrect_diagnoses         2.5
23   Argerich                                 other        21.5
24  Rivadavia                                delays        55.4
25  Rivadavia  inappropriate_interpersonal_behavior        53.5
26  Rivadavia         inefficient_medical_treatment        13.9
27  Rivadavia                    bad_infrastructure        21.8
28  Rivadavia                   incorrect_diagnoses         6.9
29  Rivadavia                                 other        11.9

In [31]:
filas = []
for hosp in df["hospital"].unique():
    sub = df[df["hospital"] == hosp]
    total = len(sub)
    conteo = Counter(cat for lista in sub["categorias_lista"] for cat in lista)
    fila = {"hospital": hosp}
    for cat in CATEGORIAS:
        fila[cat] = round(conteo.get(cat, 0) / total * 100, 1)
    filas.append(fila)

tabla_ancha = pd.DataFrame(filas)
tabla_ancha.to_csv("categorias_por_hospital_ancho.csv", index=False, encoding="utf-8-sig")
print("Guardado: categorias_por_hospital_ancho.csv")
tabla_ancha

Guardado: categorias_por_hospital_ancho.csv

,hospital,delays,inappropriate_interpersonal_behavior,inefficient_medical_treatment,bad_infrastructure,incorrect_diagnoses,other
0,Alvarez,46.4,61.9,17.9,8.9,4.2,16.7
1,Penna,59.2,46.4,13.6,16.8,4.0,15.2
2,Durand,58.6,47.1,26.7,21.5,5.2,15.2
3,Argerich,57.7,45.4,10.4,14.1,2.5,21.5
4,Rivadavia,55.4,53.5,13.9,21.8,6.9,11.9

In [32]:
#Thinking for a pictogram

In [33]:
total = len(df)
conteo = Counter(cat for lista in df["categorias_lista"] for cat in lista)

NOMBRES = {
    "delays": "Demoras",
    "inappropriate_interpersonal_behavior": "Mal trato",
    "inefficient_medical_treatment": "Tratamiento deficiente",
    "bad_infrastructure": "Infraestructura",
    "incorrect_diagnoses": "Diagnóstico erróneo",
    "other": "Otro",
}

filas = []
for cat, n in conteo.most_common():
    pct = n / total * 100
    filas.append({
        "categoria": NOMBRES.get(cat, cat),
        "cantidad": n,
        "porcentaje": round(pct, 1),
        "de_cada_10": round(pct / 10, 1)
    })

tabla_general = pd.DataFrame(filas)
tabla_general.to_csv("categorias_general.csv", index=False, encoding="utf-8-sig")
tabla_general

                categoria  cantidad  porcentaje  de_cada_10
0                 Demoras       414        55.3         5.5
1               Mal trato       380        50.8         5.1
2  Tratamiento deficiente       129        17.2         1.7
3                    Otro       123        16.4         1.6
4         Infraestructura       122        16.3         1.6
5     Diagnóstico erróneo        33         4.4         0.4